### ISSUE TITLE
Linking CXX shared library libps_roi_align.so Error running link command: No such file or directory

### ISSUE THREAD

**Issue by KyuBeomlee123** [HiKapok/PSROIAlign#1]
Hello! 

I want to import your Light-Head RCNN code. Then i have tried to build PSROIAlign but some trouble has occured. 

when  trying to make:

>[ 10%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/cuda_compile_generated_rotated_ps_roi_align_grad_op.cu.o
 .....
[100%] Linking CXX shared library libps_roi_align.so 
Error running link command: No such file or directory
CMakeFiles/ps_roi_align.dir/build.make:236: recipe for target 'libps_roi_align.so' failed
make[2]: *** [libps_roi_align.so] Error 2
make[2]: *** Deleting file 'libps_roi_align.so'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ps_roi_align.dir/all' failed
make[1]: *** [CMakeFiles/ps_roi_align.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I tried using python2 and tensorflow 1.8. How can I solve this problem?

**Comment by HiKapok** [comment]
which file or directory？can you find that？

**Comment by KyuBeomlee123** [comment]
Unfortunately, I can not find file or directory. I trying to find what is problem. In my opinion, the problem is associated with build/CMakeFiles/ps_roi_align.dir/link.txt and build.make.

**Comment by HiKapok** [comment]
did you follow readme？what,s your gcc version

**Comment by KyuBeomlee123** [comment]
Yes i follow readme. Gcc version is 5.4.0 and cuda=9.0 cudnn=7.0

**Comment by KyuBeomlee123** [comment]
I solved this problem! The reason is wrongly written build/CMakeFiles/ps_roi_align.dir/link.txt.

before:
[link.txt](https://github.com/HiKapok/PSROIAlign/files/2086462/link.txt)
after I revised:
[link.txt](https://github.com/HiKapok/PSROIAlign/files/2086463/link.txt)
Then it works! libps_roi_align.so is generated!

**Comment by Issuenate** [comment]
Hi, i also met the same problem, however i can't find the difference between these two link.txt files.
Can you tell me what did you revise? I can only find you delete some spaces inside the file.

I'm using ubuntu16.4, cuda8, python2, Gcc version is 5.4.0. 
Thanks !`

and this is my link.txt
[link.txt](https://github.com/HiKapok/PSROIAlign/files/2632574/link.txt)

`
